events {}

http{   

      server {

             include /etc/nginx/mime.types;  ## mime types for nginx. 

               listen 80;   port number for nginx to listen on.
               server_name _;  ## server name, _ means it will respond to any server name.
               
               root /etc/nginx/website;	 ## root directory for the website files.     
      
      }

} 
